include:
  # You can override the included template(s) by including variable overrides
  # SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
  # Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
  - template: Security/SAST.gitlab-ci.yml
  - project: kmohrf/gitlab-recipes
    ref: main
    file: '/templates/python-lib.gitlab-ci.yml'

variables:
  DEBBUILD_IMAGE: git-registry.hack-hro.de:443/kmohrf/docker-recipes/debbuild-python:bullseye
  DPKG_INSTALL_DISTRIBUTION: bullseye

test::python:
  extends: .run_tox
  image: $IMAGE
  parallel:
    matrix:
      - IMAGE:
        - $DEBBUILD_PY_BULLSEYE

test::libjs-crypto:
  image: mcr.microsoft.com/playwright:focal
  rules:
    - changes:
        - memoorje/crypto/*
        - libjs/crypto/**/*
  before_script:
    - apt update -y && apt install -y python3-pycryptodome
    - cd libjs/crypto
    - npm ci
  script:
    - npm run test -- --browser all
