include:
  # You can override the included template(s) by including variable overrides
  # SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
  # Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
  - template: Security/SAST.gitlab-ci.yml
  - project: kmohrf/gitlab-recipes
    ref: main
    file: '/templates/main.gitlab-ci.yml'

stages:
  - test
  - build
  - deploy

variables:
  DEBBUILD_IMAGE: git-registry.hack-hro.de:443/kmohrf/docker-recipes/debbuild-python:bullseye
  DPKG_INSTALL_DISTRIBUTION: bullseye

test::python:
  before_script:
    - apt update -y && apt install -y cargo python3-django
    - cargo install --git https://github.com/dsprenkels/sss-cli --branch v0.1
    - python3 -m django compilemessages
  parallel:
    matrix:
      - IMAGE:
        - $DEBBUILD_PY_BULLSEYE

.build-docker-image:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --force
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${PUBLISH_VERSION}"
      --skip-tls-verify

deploy::docker:
  extends: .build-docker-image
  variables:
    PUBLISH_VERSION: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG

deploy::docker-rolling:
  extends: .build-docker-image
  variables:
    PUBLISH_VERSION: rolling
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_failure: true
