include:
  # You can override the included template(s) by including variable overrides
  # SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
  # Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
  - template: Security/SAST.gitlab-ci.yml
  - project: kmohrf/gitlab-recipes
    ref: main
    file: '/templates/main.gitlab-ci.yml'

variables:
  DEBBUILD_IMAGE: git-registry.hack-hro.de:443/kmohrf/docker-recipes/debbuild-python:bullseye
  DPKG_INSTALL_DISTRIBUTION: bullseye

test::python:
  extends: .run_tox
  image: $IMAGE
  parallel:
    matrix:
      - IMAGE:
        - $DEBBUILD_PY_BULLSEYE
