# Generated by Django 3.2.9 on 2022-01-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0031_auto_20220117_1146'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_internal',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DU', 'Monthly Due'), ('CR', 'Credit'), ('RF', 'Refund')], default='CR', max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='capsule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memoorje.capsule'),
        ),
    ]
