# Generated by Django 3.2.9 on 2022-01-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20220119_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DU', 'Monthly Due'), ('CR', 'Credit'), ('RF', 'Refund')], max_length=2),
        ),
    ]
