# Generated by Django 3.2.9 on 2022-01-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='booked_at',
            new_name='booked_on',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
