# Generated by Django 3.2.9 on 2022-01-20 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memoorje', '0031_auto_20220117_1146'),
        ('accounting', '0004_auto_20220119_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='capsule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='memoorje.capsule'),
        ),
    ]
