# Generated by Django 3.2.9 on 2022-02-16 11:03

from django.db import migrations, models
import django.db.models.deletion
import memoorje.accounting.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_expense_expensetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=memoorje.accounting.models.CurrencyField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.expensetype'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=memoorje.accounting.models.CurrencyField(decimal_places=2, max_digits=8),
        ),
    ]
