# Generated by Django 3.2.7 on 2021-09-16 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0005_alter_capsule_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capsule',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capsule',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capsule',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
