# Generated by Django 3.2.7 on 2021-09-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0006_auto_20210916_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
