# Generated by Django 3.2.7 on 2021-09-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0008_capsulecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsulecontent',
            name='metadata',
            field=models.BinaryField(null=True),
        ),
    ]
