# Generated by Django 3.2.7 on 2021-09-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0009_capsulecontent_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsulecontent',
            name='metadata',
            field=models.BinaryField(editable=True),
        ),
    ]
