# Generated by Django 3.2.7 on 2021-09-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0011_capsulecontent_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsulecontent',
            name='data',
            field=models.FileField(upload_to=''),
        ),
    ]
