# Generated by Django 3.2.7 on 2021-10-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0016_capsulereceiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsulereceiver',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
