# Generated by Django 3.2.7 on 2021-10-27 08:57

from django.db import migrations, models
import django.db.models.deletion
import djeveric.fields
import memoorje.data_storage.fields
import memoorje.data_storage.storage
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0017_capsulereceiver_is_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsulecontent',
            name='data',
            field=memoorje.data_storage.fields.CapsuleDataField(storage=memoorje.data_storage.storage.CapsuleDataStorage(location=pathlib.PurePosixPath('/home/robert/memoorje/media/data')), upload_to=''),
        ),
        migrations.AlterField(
            model_name='capsulecontent',
            name='metadata',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='capsulereceiver',
            name='is_email_confirmed',
            field=djeveric.fields.ConfirmationField(default=False),
        ),
        migrations.CreateModel(
            name='Keyslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('purpose', models.CharField(choices=[('pwd', 'Password'), ('sss', 'Sss')], max_length=3)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoorje.capsule')),
            ],
        ),
    ]
