# Generated by Django 3.2.7 on 2021-10-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0018_auto_20211027_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsulecontent',
            name='metadata',
            field=models.BinaryField(),
        ),
    ]
