# Generated by Django 3.2.8 on 2021-10-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0018_auto_20211027_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remind_interval',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
