# Generated by Django 3.2.8 on 2021-10-29 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0019_user_remind_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_reminder_sent_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to=settings.AUTH_USER_MODEL),
        ),
    ]
