# Generated by Django 3.2.9 on 2021-11-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0024_auto_20211115_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partialkey',
            name='capsule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_keys', to='memoorje.capsule'),
        ),
    ]
