# Generated by Django 3.2.9 on 2021-11-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0025_auto_20211115_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyslot',
            name='capsule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyslots', to='memoorje.capsule'),
        ),
    ]
