# Generated by Django 3.2.9 on 2022-01-04 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0026_alter_keyslot_capsule'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsulereceiver',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
