# Generated by Django 3.2.9 on 2022-01-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0028_partialkey_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='are_partial_key_invitations_sent',
            field=models.BooleanField(default=False),
        ),
    ]
