# Generated by Django 3.2.9 on 2022-01-05 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0029_capsule_are_partial_key_invitations_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustee',
            name='capsule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustees', to='memoorje.capsule'),
        ),
    ]
