# Generated by Django 3.2.9 on 2022-01-17 10:46

from django.db import migrations, models
import django.db.models.deletion
import djeveric.fields
import djeveric.models


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0030_alter_trustee_capsule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_email_confirmed', djeveric.fields.ConfirmationField(default=False)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='memoorje.capsule')),
            ],
            options={
                'unique_together': {('capsule', 'email')},
            },
            bases=(djeveric.models.ConfirmableModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='CapsuleReceiver',
        ),
    ]
