# Generated by Django 3.2.9 on 2022-02-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0031_auto_20220117_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsulerecipient',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
