# Generated by Django 3.2.9 on 2022-02-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0032_capsulerecipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyslot',
            name='recipient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='memoorje.capsulerecipient'),
        ),
    ]
