# Generated by Django 3.2.9 on 2022-02-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0035_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latest_notified_journal_entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memoorje.journalentry'),
        ),
    ]
