# Generated by Django 3.2.9 on 2022-02-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0037_alter_journalentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
