# Generated by Django 3.2.9 on 2022-02-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoorje', '0038_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='de', max_length=7),
        ),
    ]
