/* tslint:disable */
/* eslint-disable */
/**
 * Memoorje API
 * Sicherer, selbstverwalteter digitaler Nachlass für alle
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Capsule
 */
export interface Capsule {
    /**
     * 
     * @type {Date}
     * @memberof Capsule
     */
    readonly createdOn: Date;
    /**
     * 
     * @type {string}
     * @memberof Capsule
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Capsule
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Capsule
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof Capsule
     */
    readonly updatedOn: Date;
    /**
     * 
     * @type {string}
     * @memberof Capsule
     */
    readonly url: string;
}

export function CapsuleFromJSON(json: any): Capsule {
    return CapsuleFromJSONTyped(json, false);
}

export function CapsuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Capsule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdOn': (new Date(json['createdOn'])),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'id': json['id'],
        'name': json['name'],
        'updatedOn': (new Date(json['updatedOn'])),
        'url': json['url'],
    };
}

export function CapsuleToJSON(value?: Capsule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
    };
}


