/* tslint:disable */
/* eslint-disable */
/**
 * Memoorje API
 * Sicherer, selbstverwalteter digitaler Nachlass für alle
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CapsuleContent
 */
export interface CapsuleContent {
    /**
     * 
     * @type {string}
     * @memberof CapsuleContent
     */
    capsule: string;
    /**
     * 
     * @type {string}
     * @memberof CapsuleContent
     */
    metadata: string;
    /**
     * 
     * @type {string}
     * @memberof CapsuleContent
     */
    data: string;
}

export function CapsuleContentFromJSON(json: any): CapsuleContent {
    return CapsuleContentFromJSONTyped(json, false);
}

export function CapsuleContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CapsuleContent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'capsule': json['capsule'],
        'metadata': json['metadata'],
        'data': json['data'],
    };
}

export function CapsuleContentToJSON(value?: CapsuleContent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'capsule': value.capsule,
        'metadata': value.metadata,
        'data': value.data,
    };
}


