/* tslint:disable */
/* eslint-disable */
/**
 * Memoorje API
 * Sicherer, selbstverwalteter digitaler Nachlass für alle
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Default serializer used for user login. Please keep in mind that
 * the authentication is done by separate function defined by
 * :ref:`login-authenticator-setting` setting.
 * 
 * By default :ref:`login-authenticator-setting` function will use
 * :ref:`user-login-fields-setting` setting to extract the login field
 * from the validated serializer data either by using the 'login' key
 * (which is used here) or the specific login field name(s)
 * (e.g. 'username', 'email').
 * 
 * If you want different behavior, you need to
 * override :ref:`login-authenticator-setting` in your settings.
 * @export
 * @interface DefaultLogin
 */
export interface DefaultLogin {
    /**
     * 
     * @type {string}
     * @memberof DefaultLogin
     */
    login: string;
    /**
     * 
     * @type {string}
     * @memberof DefaultLogin
     */
    password: string;
}

export function DefaultLoginFromJSON(json: any): DefaultLogin {
    return DefaultLoginFromJSONTyped(json, false);
}

export function DefaultLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultLogin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'login': json['login'],
        'password': json['password'],
    };
}

export function DefaultLoginToJSON(value?: DefaultLogin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'login': value.login,
        'password': value.password,
    };
}


