/* tslint:disable */
/* eslint-disable */
/**
 * Memoorje API
 * Sicherer, selbstverwalteter digitaler Nachlass für alle
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Default serializer used for sending reset password link.
 * 
 * It will use :ref:`send-reset-password-link-serializer-use-email-setting`
 * setting.
 * @export
 * @interface DefaultSendResetPasswordLink
 */
export interface DefaultSendResetPasswordLink {
    /**
     * 
     * @type {string}
     * @memberof DefaultSendResetPasswordLink
     */
    login: string;
}

export function DefaultSendResetPasswordLinkFromJSON(json: any): DefaultSendResetPasswordLink {
    return DefaultSendResetPasswordLinkFromJSONTyped(json, false);
}

export function DefaultSendResetPasswordLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultSendResetPasswordLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'login': json['login'],
    };
}

export function DefaultSendResetPasswordLinkToJSON(value?: DefaultSendResetPasswordLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'login': value.login,
    };
}


