/* tslint:disable */
/* eslint-disable */
/**
 * Memoorje API
 * Sicherer, selbstverwalteter digitaler Nachlass für alle
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Logout
 */
export interface Logout {
    /**
     * 
     * @type {boolean}
     * @memberof Logout
     */
    revokeToken?: boolean;
}

export function LogoutFromJSON(json: any): Logout {
    return LogoutFromJSONTyped(json, false);
}

export function LogoutFromJSONTyped(json: any, ignoreDiscriminator: boolean): Logout {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'revokeToken': !exists(json, 'revokeToken') ? undefined : json['revokeToken'],
    };
}

export function LogoutToJSON(value?: Logout | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'revokeToken': value.revokeToken,
    };
}


