/* tslint:disable */
/* eslint-disable */
/**
 * Memoorje API
 * Sicherer, selbstverwalteter digitaler Nachlass für alle
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedCapsule
 */
export interface PatchedCapsule {
    /**
     * 
     * @type {string}
     * @memberof PatchedCapsule
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCapsule
     */
    readonly url?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCapsule
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCapsule
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCapsule
     */
    readonly createdOn?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCapsule
     */
    readonly updatedOn?: Date;
}

export function PatchedCapsuleFromJSON(json: any): PatchedCapsule {
    return PatchedCapsuleFromJSONTyped(json, false);
}

export function PatchedCapsuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCapsule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'createdOn': !exists(json, 'createdOn') ? undefined : (new Date(json['createdOn'])),
        'updatedOn': !exists(json, 'updatedOn') ? undefined : (new Date(json['updatedOn'])),
    };
}

export function PatchedCapsuleToJSON(value?: PatchedCapsule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
    };
}


