/* tslint:disable */
/* eslint-disable */
/**
 * Memoorje API
 * Sicherer, selbstverwalteter digitaler Nachlass für alle
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Default serializer used for user profile. It will use these:
 * 
 * * User fields
 * * :ref:`user-hidden-fields-setting` setting
 * * :ref:`user-public-fields-setting` setting
 * * :ref:`user-editable-fields-setting` setting
 * 
 * to automagically generate the required serializer fields.
 * @export
 * @interface PatchedDefaultUserProfile
 */
export interface PatchedDefaultUserProfile {
    /**
     * 
     * @type {number}
     * @memberof PatchedDefaultUserProfile
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedDefaultUserProfile
     */
    readonly email?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedDefaultUserProfile
     */
    name?: string;
}

export function PatchedDefaultUserProfileFromJSON(json: any): PatchedDefaultUserProfile {
    return PatchedDefaultUserProfileFromJSONTyped(json, false);
}

export function PatchedDefaultUserProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedDefaultUserProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function PatchedDefaultUserProfileToJSON(value?: PatchedDefaultUserProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


