/* tslint:disable */
/* eslint-disable */
/**
 * Memoorje API
 * Sicherer, selbstverwalteter digitaler Nachlass für alle
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedCapsuleContent
 */
export interface PatchedCapsuleContent {
    /**
     * 
     * @type {string}
     * @memberof PatchedCapsuleContent
     */
    capsule?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCapsuleContent
     */
    data?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedCapsuleContent
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedCapsuleContent
     */
    metadata?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCapsuleContent
     */
    readonly url?: string;
}

export function PatchedCapsuleContentFromJSON(json: any): PatchedCapsuleContent {
    return PatchedCapsuleContentFromJSONTyped(json, false);
}

export function PatchedCapsuleContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCapsuleContent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'capsule': !exists(json, 'capsule') ? undefined : json['capsule'],
        'data': !exists(json, 'data') ? undefined : json['data'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function PatchedCapsuleContentToJSON(value?: PatchedCapsuleContent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'capsule': value.capsule,
        'data': value.data,
        'metadata': value.metadata,
    };
}


