/* tslint:disable */
/* eslint-disable */
/**
 * Memoorje API
 * Sicherer, selbstverwalteter digitaler Nachlass für alle
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyRegistration
 */
export interface VerifyRegistration {
    /**
     * 
     * @type {string}
     * @memberof VerifyRegistration
     */
    userId: string;
    /**
     * 
     * @type {number}
     * @memberof VerifyRegistration
     */
    timestamp: number;
    /**
     * 
     * @type {string}
     * @memberof VerifyRegistration
     */
    signature: string;
}

export function VerifyRegistrationFromJSON(json: any): VerifyRegistration {
    return VerifyRegistrationFromJSONTyped(json, false);
}

export function VerifyRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyRegistration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'timestamp': json['timestamp'],
        'signature': json['signature'],
    };
}

export function VerifyRegistrationToJSON(value?: VerifyRegistration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'timestamp': value.timestamp,
        'signature': value.signature,
    };
}


