/* tslint:disable */
/* eslint-disable */
/**
 * Memoorje API
 * Sicherer, selbstverwalteter digitaler Nachlass für alle
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyEmail
 */
export interface VerifyEmail {
    /**
     * 
     * @type {string}
     * @memberof VerifyEmail
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyEmail
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof VerifyEmail
     */
    timestamp: number;
    /**
     * 
     * @type {string}
     * @memberof VerifyEmail
     */
    signature: string;
}

export function VerifyEmailFromJSON(json: any): VerifyEmail {
    return VerifyEmailFromJSONTyped(json, false);
}

export function VerifyEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyEmail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'email': json['email'],
        'timestamp': json['timestamp'],
        'signature': json['signature'],
    };
}

export function VerifyEmailToJSON(value?: VerifyEmail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'email': value.email,
        'timestamp': value.timestamp,
        'signature': value.signature,
    };
}


